name: wolpray_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: any
  font_awesome_flutter:
  parallax_swiper: ^0.0.1
  flutter_swiper: ^1.1.6
  provider:
  simple_animations:
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.5
   


  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.0
  rxdart: ^0.22.0
  image_picker:
  mime_type:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/wonder.png"
  adaptive_icon_background: "lib/assets/wonder.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - lib/assets/img/
    - lib/assets/img/icons/
    
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Piedra
      fonts:
        - asset: lib/fonts/Piedra-Regular.ttf
    - family: Lemonada
      fonts:
        - asset: lib/fonts/static/Lemonada-Bold.ttf
          weight: 700
        - asset: lib/fonts/static/Lemonada-Light.ttf
          weight:  300
        - asset: lib/fonts/static/Lemonada-Medium.ttf
          weight:  500
        - asset: lib/fonts/static/Lemonada-Regular.ttf
          weight:  400
        - asset: lib/fonts/static/Lemonada-SemiBold.ttf
          weight:  600
  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
